version: '2.0'

services:
 studentmanager:
   image: localhost:5000/student-manager-service:0.0.1-SNAPSHOT
   environment:
   - VERSION=0.0.2
   ports:
   - "9091-9099:9090"
   networks:
   - local_network

 nginx:
     image: nginx
     container_name: "studentmanager-lb"
     hostname: studentmanager-lb
     depends_on:
     - studentmanager
     ports:
     - "9005:9005"
     volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     networks:
     - local_network
   
networks:
 local_network:
   external: true
